######################################################################
# Automatically generated by qmake (2.01a) Mon May 13 14:13:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tray.h
SOURCES += main.cc tray.cc
